# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - main

pool:
  name: kaif-selfhosted

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    #javaHomeOption: 'Path'
    #jdkDirectory: '/usr/lib/jvm/java-21-openjdk-amd64'
    publishJUnitResults: false
    goals: 'clean package'

- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'ssh-local'
    sourceFolder: '$(System.DefaultWorkingDirectory)'
    contents: '**/target/*.jar'
    targetFolder: '/home/kaif/azure-vm-java-app'

- task: SSH@0
  inputs:
    sshEndpoint: 'ssh-local'
    runOptions: 'commands'
    commands: |
      cd /home/kaif/azure-vm-java-app
      pwd && sleep 6
      pkill -f "java -jar" || true
      nohup bash -c 'java -jar target/simple-java-app-1.0.jar' \
      > app.log 2>&1 < /dev/null &
